[colors]
background = #131008
background-alt = #a3a47e
foreground = #c4c3c1
primary = #a3a47e
secondary = #81a1c1
alert = #63593a
disabled = #6b6557
bar-bg = #99131008

[bar/main]
font-0 = "Inconsolata Nerd Font Mono:size=11;2"
font-1 = "Inconsolata Nerd Font Mono:size=11:weight=bold;2"
font-2 = "Font Awesome 7 Free:size=11;2"
font-3 = "Font Awesome 7 Free Solid:size=7;2"
font-4 = "Inconsolata Nerd Font Mono:size=16;2"
font-5 = "Inconsolata Nerd Font Mono:size=18;2"
offset-y = 5
offset-x = 5
width = 99.2679%
height = 25
fixed-center = true
background = ${colors.bar-bg}
foreground = ${colors.foreground}
line-size = 3
radius = 0
padding-right = 2pt
module-margin-left = 2pt
module-margin-right = 2pt
separator = |
separator-foreground = ${colors.disabled}
modules-left = i3 pulseaudio xkeyboard 
modules-center = date 
modules-right = eth wlan filesystem temperature memory cpu battery powermenu
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
override-redirect = true
wm-restack = i3

[module/systray]
type = internal/tray
format-margin = 0
tray-spacing = 8

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %mountpoint% %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume>
label-volume = %decibels% dB
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-foreground = ${colors.primary}
label-muted = muted
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard
format = <label-layout> <label-indicator>
format-spacing = 2pt
label-layout = %layout% 
label-indicator = %name%
label-layout-foreground = ${colors.primary}
label-indicator-on-numlock = 
label-indicator-on-scrolllock = 
label-indicator-padding = 2
label-indicator-margin = 2
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰍛 "
format-prefix-font = 3
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected

[module/wlan]
type = custom/script
exec = ~/.config/polybar/scripts/network.sh status
interval = 5
tail = true
label = %output%
label-font = 5
label-foreground = ${colors.primary}
label-padding = 1
label-disconnected = 󰈬 disconnected
label-disconnected-font = 5
label-disconnected-padding = 1
label-disconnected-foreground = ${colors.disabled}
click-left = ~/.config/rofi/network-manager/hypr-net.sh

[module/eth]
inherit = network-base
interface-type = wired
interface = CloudflareWARP
unknown-as-up = true
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = 󰢾 %{F#eceff4}%local_ip%
label-connected-foreground = ${colors.primary}
label-disconnected = 󰞃 disconnected
label-disconnected-foreground = ${colors.secondary}
speed-unit = ''

[module/date]
type = custom/script
exec = ~/.config/polybar/modules/datetime.sh
interval = 300
tail = true
label = %output%
label-foreground = ${colors.background}
label-background = ${colors.primary}
label-padding-left = 2
label-padding-right = 2

; custom modules
[module/i3]
type = internal/i3
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = true
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.alert}
label-focused = %name%: 
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.background}
label-focused-padding = 3pt
label-unfocused =  
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 3pt
label-urgent =  
label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.background}
label-urgent-padding = 3pt

[module/powermenu]
type = custom/menu
format-foreground = ${colors.foreground}
format-background = ${colors.background}
label-open = "⏻ "
label-close = " "
label-close-foreground = ${colors.foreground}
label-separator = " "
label-separator-foreground = ${colors.foreground}
menu-0-1 = 
menu-0-1-exec = systemctl reboot
menu-0-1-foreground = ${colors.foreground}
menu-0-0 = " "
menu-0-0-exec = systemctl poweroff
menu-0-0-foreground = ${colors.foreground}


[module/polypomo]
type = custom/script
exec = /home/joao/.config/polybar/modules/polypomo
tail = true
label = %output%
click-left = /home/joao/.config/polybar/modules/polypomo toggle
click-right = /home/joao/.config/polybar/modules/polypomo end
click-middle = /home/joao/.config/polybar/modules/polypomo lock
scroll-up = /home/joao/.config/polybar/modules/polypomo time +60
scroll-down = /home/joao/.config/polybar/modules/polypomo time -60

[module/temperature]
type = internal/temperature
warn-temperature = 80
format = <label>
format-warn = <label-warn>
label = %{F#a3a47e} %{F-}%temperature-c%
label-warn =  %temperature-c%
label-warn-foreground = #63593a

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 98

format-charging = <animation-charging> <label-charging>
label-charging = %percentage%%
label-charging-foreground = ${colors.primary}
label-charging-font = 1
animation-charging-0 = 
animation-charging-1 = 
animation-charging-framerate = 750
animation-charging-foreground = ${colors.primary}
animation-charging-font = 4

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
label-discharging-foreground = ${colors.foreground}
label-discharging-font = 1
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-font = 4
ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1-foreground = ${colors.alert}
ramp-capacity-2-foreground = ${colors.primary}
ramp-capacity-3-foreground = ${colors.primary}
ramp-capacity-4-foreground = ${colors.primary}

format-full = <label-full>
label-full =  %percentage%%

[settings]
screenchange-reload = true
compositing-background = source
compositing-overline = over
compositing-underline = over
compositing-foreground = over
compositing-border = over
pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini
